// Code generated by "typemapper "; DO NOT EDIT.

// +build !typemapper

package consul

import structs "github.com/hashicorp/consul/agent/structs"

func ServiceNodeToNodeService(src *structs.ServiceNode, dst *structs.NodeService) {
	if dst == nil {
		return
	}
	dst.Kind = src.ServiceKind
	dst.ID = src.ServiceID
	dst.Service = src.ServiceName
	dst.Tags = src.ServiceTags
	dst.Address = src.Address
	dst.Meta = src.ServiceMeta
	dst.Port = src.ServicePort
	dst.Weights = &src.ServiceWeights
	dst.EnableTagOverride = src.ServiceEnableTagOverride
	dst.ProxyDestination = src.ServiceProxyDestination
	dst.Proxy = src.ServiceProxy
	dst.Connect = src.ServiceConnect
	dst.RaftIndex = src.RaftIndex
	return
}
