// Code generated by "typemapper "; DO NOT EDIT.

// +build !typemapper

package testdata

import "testing"

func TestMapSliceSrcDestParams(t *testing.T)                        {}
func TestMapSliceSrcDestParamsError(t *testing.T)                   {}
func TestMapSliceSrcParamsDestConst(t *testing.T)                   {}
func TestMapSliceSrcParamsDestConstTypeAlias(t *testing.T)          {}
func TestMapSliceSrcParamsDestConstTypeAliasError(t *testing.T)     {}
func TestMapSliceSrcParamsTypeAliasDestConst(t *testing.T)          {}
func TestMapSliceSrcParamsTypeAliasDestConstTypeAlias(t *testing.T) {}
