// Code generated by "typemapper "; DO NOT EDIT.

// +build !typemapper

package testdata

func MapSliceSrcDestParams(src []string, dst []string) {
	dst = dst[:0]
	for _, x := range src {
		dst = append(dst, x)
	}
	return
}
func MapSliceSrcDestParamsError(src []string, dst []string) error {
	dst = dst[:0]
	for _, x := range src {
		dst = append(dst, x)
	}
	return nil
}
func MapSliceSrcParamsDestConst(src []string) []string {
	var dst []string
	for _, x := range src {
		dst = append(dst, x)
	}
	return dst
}
func MapSliceSrcParamsDestConstTypeAlias(src []string) []stringAlias {
	var dst []stringAlias
	for _, x := range src {
		dst = append(dst, stringAlias(x))
	}
	return dst
}
func MapSliceSrcParamsDestConstTypeAliasError(src []string) ([]stringAlias, error) {
	var dst []stringAlias
	for _, x := range src {
		dst = append(dst, stringAlias(x))
	}
	return dst, nil
}
func MapSliceSrcParamsTypeAliasDestConst(src []stringAlias) []string {
	var dst []string
	for _, x := range src {
		dst = append(dst, string(x))
	}
	return dst
}
func MapSliceSrcParamsTypeAliasDestConstTypeAlias(src []stringAlias) []stringAlias {
	var dst []stringAlias
	for _, x := range src {
		dst = append(dst, x)
	}
	return dst
}
