// Code generated by "typemapper "; DO NOT EDIT.

// +build !typemapper

package testdata

import "testing"

func TestMapStructPtrSrcDestParams(t *testing.T)            {}
func TestMapStructPtrSrcParamsDestConst(t *testing.T)       {}
func TestMapStructPtrSrcRecvDestConst(t *testing.T)         {}
func TestMapStructPtrSrcRecvPtrDestConst(t *testing.T)      {}
func TestMapStructPtrSrcRecvPtrDestConstError(t *testing.T) {}
func TestMapStructSrcDestParams(t *testing.T)               {}
func TestMapStructSrcDstParamsError(t *testing.T)           {}
func TestMapStructSrcParamsDestConst(t *testing.T)          {}
func TestMapStructSrcParamsDestConstError(t *testing.T)     {}
func TestMapStructSrcParamsPtrDestConst(t *testing.T)       {}
func TestMapStructSrcRecvDestConst(t *testing.T)            {}
func TestMapStructSrcRecvDestParams(t *testing.T)           {}
func TestMapStructSrcRecvPtrDestConst(t *testing.T)         {}
