// Code generated by "typemapper "; DO NOT EDIT.

// +build !typemapper

package main

func MapFooToBar(src Foo) Bar {
	dst := Bar{}
	dst.FieldOne = src.FieldOne
	// no match for "Field2"
	return dst
}
